# Generated by Django 3.0.7 on 2020-06-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
